config/routes.rb
Rails.application.routes.draw do
  resources :leaderboards

end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: [:show, :edit, :update, :destroy]

  # GET /leaderboards
  # GET /leaderboards.json
  def index
    @leaderboards = Leaderboard.all.order('score DESC').limit(10)
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)

    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully created.' }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1
  # PATCH/PUT /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: 'Leaderboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      @leaderboard = Leaderboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaderboard_params
      params.require(:leaderboard).permit(:position, :name, :score, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FingerDrumLeaderboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leaderboards/_form.html.erb
<%= form_for(@leaderboard) do |f| %>
  <% if @leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% @leaderboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Name</th>
      <th>Score</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboards.each do |leaderboard| %>
      <tr>
        <td><%= leaderboard.position %></td>
        <td><%= leaderboard.name %></td>
        <td><%= leaderboard.score %></td>
        <td><%= leaderboard.email %></td>
        <td><%= link_to 'Show', leaderboard %></td>
        <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
        <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaderboard', new_leaderboard_path %>

app/views/leaderboards/new.html.erb
<h1>New Leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @leaderboard.position %>
</p>

<p>
  <strong>Name:</strong>
  <%= @leaderboard.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @leaderboard.score %>
</p>

<p>
  <strong>Email:</strong>
  <%= @leaderboard.email %>
</p>

<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>